### ISSUE TITLE
folder "ssl"

### ISSUE THREAD

**Issue by BeckeBauer** [accolon/parsedmarc-dockerized#1]
Installation process was interrupted due to the missing folder "ssl" required by docker-compose.yml:
```
    volumes:
     ...
      - ./data/conf/nginx/ssl/:/etc/nginx/ssl/:rw
      ...
```
Maybe, it can be included into the repository? Thanks for the work, by the way

**Comment by accolon** [comment]
Thanks! Most work was done by others, I just modified parts for my own needs (especially ARM compatibility) and put it here in case people might find it useful.

Docker Compose should actually create the `ssl` folder automatically (just tried), but it probably doesn't hurt if it is there by default.
